DevExpress/AjaxControlToolkit

AjaxControlToolkit/AlwaysVisibleControl/AlwaysVisibleControlExtender.cs, AjaxControlToolkit/Animation/AnimationExtender.cs, AjaxControlToolkit/DropDown/DropDownExtender.cs, AjaxControlToolkit/DropShadow/DropShadowExtender.cs, AjaxControlToolkit/DynamicPopulate/DynamicPopulateExtender.cs, AjaxControlToolkit/HoverExtender/HoverExtender.cs, AjaxControlToolkit/HoverMenu/HoverMenuExtender.cs, AjaxControlToolkit/ModalPopup/ModalPopupExtender.cs, AjaxControlToolkit/PopupControl/PopupControlExtender.cs, AjaxControlToolkit/PopupExtender/PopupExtender.cs, AjaxControlToolkit/ResizableControl/ResizableControlExtender.cs, AjaxControlToolkit/RoundedCorners/RoundedCornersExtender.cs
TargetControlType expanded for some controls to reflect pre-15.1 behavior
=> Resolve #3

README.md
=> Add installer shield to README

AjaxControlToolkit/AlwaysVisibleControl/AlwaysVisibleControlExtender.cs
add UpdateProgress TargetConrolType for AlwaysVisibleControlExtender
=> Resolve #54

AjaxControlToolkit/HtmlEditor/Popups/Popup.cs
restore HtmlEditor popup buttons text
=> Resolve #47

AjaxControlToolkit.Jasmine/Global.asax.cs, AjaxControlToolkit.Jasmine/Web.config, AjaxControlToolkit.SampleSite/Web.config, AjaxControlToolkit/AjaxControlToolkitConfigSection.cs, AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs, AjaxControlToolkit/AjaxFileUpload/AjaxFileUploadHelper.cs, AjaxControlToolkit/ToolkitConfig.cs
replace AjaxFileUploadHelper.RootTempFolderPath with global TempFolder setting
=> Resolve #22

AjaxControlToolkit/HtmlEditor/Editor.cs
=> Resolve #70

AjaxControlToolkit.Jasmine/Suites/SlideShowTests/SlideShowTests.aspx
=> Make SlideShow test condition more precise

appveyor.yml
remove redundant environment variable
=> Cleanup appveyor.yml

AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs
fix upload for hidden AjaxFileUpload
=> Resolve #122

AjaxControlToolkit/AjaxControlToolkit.csproj
=> Add 1591 warning suppression for Debug configuration

appveyor.yml
* Turn off `publish_wap`
* Simplify commands
* Fix formatting, order of sections
=> appveyor.yml improvements

AjaxControlToolkit/Scripts/FilteredTextBox.js
=> Resolve #197

AjaxControlToolkit/Scripts/FilteredTextBox.js
Avoid WebKit-specific code to be deprecated: https://www.chromestatus.com/features/5316065118650368
=> Resolve #198

AjaxControlToolkit/AsyncFileUpload/AsyncFileUpload.cs
Fixed unwanted session generation by AsyncFileUpload: now a cookieless session is taken into account on generating a postback URL.
=> Resolve #203

AjaxControlToolkit.SampleSite/Layout.master
=> Resolve #209

AjaxControlToolkit.Jasmine/Suites/HtmlEditorExtenderTests/HtmlEditorExtenderTests.aspx
This PR is a preparation for #279 fix.
=> Avoiding flaky tests in Firefox

AjaxControlToolkit/Scripts/Accordion.js, ReferenceCore/Documentation.cs
This PR includes client members' description into the documentation.
Before: https://github.com/DevExpress/AjaxControlToolkit/wiki/Accordion
After: https://github.com/MikhailTymchukDX/AjaxControlToolkit/wiki/Accordion
=> Accordion documentation generation is fixed.

AjaxControlToolkitVsPackage/AjaxControlToolkitVsPackage.cs, AjaxControlToolkitVsPackageLegacy/AjaxControlToolkitVsPackage.cs
Current toolbox state:
New toolbox state:
=> Toolbox items are sorted

AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs, AjaxControlToolkit/AjaxFileUpload/AjaxFileUploadMode.cs, AjaxControlToolkit/Scripts/AjaxFileUpload.js
Updating comments and docs, see #425 for details.
=> Fix AjaxFileUploadMode description and AjaxFileUpload.Mode docs (Resolve #425)

AjaxControlToolkit.SampleSite/Gravatar/Gravatar.aspx, AjaxControlToolkit/Gravatar/Gravatar.cs
Added support for https image url on gravatar control
Added demo on example page
=> Added support for https image url on gravatar control

AjaxControlToolkit.Tests/HtmlEditorExtenderTests.cs, AjaxControlToolkit/HtmlEditorExtender/HtmlEditorExtender.cs
=> Allow img[src=data:image] in HtmlEditorExtender

LICENSE.txt
=> possible typo
